config/routes.rb
Rails.application.routes.draw do

  resources :affairs do
    resources :rsvps
  end

  root 'welcome#index'
  
  
  #get 'welcome/index'


  post '/affairs/new' => 'affairs#new'
  get '/affairs/:id' => 'affairs#show'
  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/affair.rb
class Affair < ActiveRecord::Base
  has_many :rsvps, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
  
end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  belongs_to :affair
end

app/controllers/affairs_controller.rb
class AffairsController < ApplicationController

 http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @affairs = Affair.all
  end

  def show
    @affair = Affair.find(params[:id])
  end

  def new
    @affair = Affair.new
  end

  def edit
    @affair = Affair.find(params[:id])
  end

  def create
    @affair = Affair.new(affair_params)

    if @affair.save
      redirect_to @affair
    else
      render 'new'
    end
  end

  def update
    @affair = Affair.find(params[:id])

    if @affair.update(affair_params)
      redirect_to @affair
    else
      render 'edit'
    end
  end

  def destroy
    @affair = Affair.find(params[:id])
    @affair.destroy

    redirect_to affairs_path
  end

  private
    def affair_params
      params.require(:affair).permit(:title,:datetime,:text,:text)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController

  #http_basic_authenticate_with name: "dhh", password: "secret", only: destroy
  
  def create
    @affair = Affair.find(params[:affair_id])
    @rsvp = @affair.rsvps.create(rsvp_params)

    redirect_to affair_path(@affair)
  end

  def destroy
    @affair = Affair.find(params[:affair_id])
    @rsvp = @affair.rsvps.find(params[:id])
    @rsvp.destroy

    redirect_to affair_path(@affair)
  end

  private
    def rsvp_params
      params.require(:rsvp).permit(:guest,:email,:body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/affairs/_form.html.erb
<%= form_for @affair do |f| %>

  <% if @affair.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%=pluralize(@affair.errors.count, "error") %>
prohibited
        this article from being saved:
      </h2>
      <ul>
        <%= @affair.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.datetime_select :datetime %><br>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
          
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/affairs/edit.html.erb
<h1>Edit Your event</h1>

<%= render 'form' %>

<%= link_to 'Back', affairs_path %>

app/views/affairs/index.html.erb
<h1>All Events!</h1>

<%= link_to 'Add a New Event', new_affair_path %>
<br><br><br>
<table>
  <tr>
    <th>Name</th>
    <th>Date and Time</th>
    <th>Address</th>
    <th>Details</th>
    <th colspan="3"></th>
  </tr>

  <% @affairs.each do |affair| %>
    <tr>
      <td><%= affair.title %></td>
      <td><%= affair.datetime %></td>
      <td><%= affair.text %><td>
      <td><%= affair.text %></td>
      <td><%= link_to 'View Details', affair_path(affair) %></td>
      <td><%= link_to 'Edit', edit_affair_path(affair) %></td>
      <td><%= link_to 'Cancel Event', affair_path(affair), 
              method: :delete,
              data: { confirm: 'Are you sure? People will be sad' } %></td>
    </tr>
  <% end %>
</table>

app/views/affairs/new.html.erb
<h1 class="new-text">New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/affairs/show.html.erb
<p>
  <strong>Event:</strong>
  <%= @affair.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @affair.datetime %>
</p>

<p>
  <strong>Location:<strong>
  <%= @affair.text %>
<p>
  <strong>Details:</strong>
  <%= @affair.text %>
</p>

<br><hr>
<br><hr>
<h2>Who's Going?</h2>
<%= render @affair.rsvps %>

<h2>RSVP Now!</h2>
<%= render 'rsvps/form' %>


<%= link_to 'Edit', edit_affair_path(@affair) %>
<%= link_to 'Back', affairs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>Event</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rsvps/_form.html.erb
<%= form_for([@affair, @affair.rsvps.build]) do |f| %>
  <p>
    <%= f.label :guest %><br>
    <%= f.text_field :guest %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p> 
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/rsvps/_rsvp.html.erb
<p>
  <strong>Guest:</strong>
  <%= rsvp.guest %>
</p>

<p>
  <strong>E-mail:</strong>
  <%= rsvp.email %>
</p>

<p>
  <strong>Comment:</strong>
  <%= rsvp.body %>
</p>

<p>
  <%= link_to 'Just kidding, not going', [rsvp.affair, rsvp],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

app/views/welcome/index.html.erb
<body class="background">
<h1 class="text">Let's have a DANCE PARTY!</h1>
<%= link_to 'New Party','affairs/new' %><br>
<%= link_to 'See all events', 'affairs' %>
</body>